export default [
    {
        id: 7,
        resolved: 1,
        audio_path: "./audios/audio4.mp3",
        agent_id: 1,
        agent_name: "Mohamed Hanini",
        date: "12/04/2024",
        title: "Resolving a Customer's Frustration: Delayed and Damaged Order Compensation",
        client_id: 2,
        client_name: "Badr Marani",
        metadata: {
            demands:
                "- The client demanded accountability for the delayed and damaged product, citing their premium payment and expectations for high-quality service.<br>- They insisted on proper follow-up to ensure no recurrence of such issues in future orders.",
            actions:
                "- The agent apologized sincerely, acknowledged the client's frustration, and committed to resolving the problem.<br>- Proposed an exchange of the damaged product with expedited shipping and covered all return costs.<br>- Offered a 20% discount on a future purchase as a gesture of goodwill.<br>- Highlighted internal process improvements to avoid similar incidents in the future.",
            conclusion:
                "- The client accepted the proposed solutions, including the replacement and compensation, but emphasized their expectation for proper handling moving forward.  ",
            next_steps:
                "- The agent committed to following up personally after the client receives the replacement to ensure satisfaction.<br>- The company will implement process reviews to address logistic and quality issues raised in this case.<br>- The client awaits delivery of the replacement and will assess the company's actions before making decisions about future purchases.",
            sentiment_desc_client:
                "The agent maintains a professional and empathetic tone throughout, focusing on resolving the issue, rebuilding trust, and ensuring the client feels valued.",
            sentiment_desc_agent:
                "The client is initially frustrated and dissatisfied but becomes cautiously hopeful as solutions are proposed, though they remain skeptical about future service reliability.",
        },
        transcriptions: [
            {
                speaker: "Agent",
                text: "صباح الخير، مرحبا بيك فخدمة زبناء Client 2. أنا اسمي إيمان، كفاش نقدر نعاونك اليوم؟",
                offset: 0,
                duration: 5,
                sentiment: "neutral",
                tag: "",
            },
            {
                speaker: "Client",
                text: "صباح الخير، عيطت ليكم حيت أنا ماعاجبنيش الحال من آخر طلبية. أنا زبون ديالكم من سنوات، ولكن هاد المرة الخدمة ماشي مقبولة نهائيا.",
                offset: 5,
                duration: 10,
                sentiment: "negative",
                proposed_answer: "",
                tag: "استياء الزبون",
            },
            {
                speaker: "Agent",
                text: "كنأسف بزاف نسمع بلي وقعات لك تجربة خايبة، سيدي. يلا ممكن تشرح لي شنو وقع، أنا هنا باش نعاونك نحل هاد المشكل.",
                offset: 16,
                duration: 9,
                sentiment: "neutral",
                proposed_answer: "",
                tag: "",
            },
            {
                speaker: "Client",
                text: "شوف، طلبت واحد المنتوج اللي مهم هدية عيد الميلاد، وماغير وصل متأخر 5 أيام ولكن حتى هو كان مخسر من الداخل. صراحة هادشي كيحبط.",
                offset: 26,
                duration: 9,
                sentiment: "negative",
                proposed_answer: "",
                tag: "إحباط الزبون",
            },
            {
                speaker: "Agent",
                text: "كنفهم الإحباط ديالك، وكنعتذر بزاف على هاد التجربة الخايبة.",
                offset: 38,
                duration: 5,
                sentiment: "neutral",
                proposed_answer: "",
                tag: "تطمين الزبون",
            },
            {
                speaker: "Client",
                text: "خلصت على التوصيل السريع، وكنت كنتسنى المنتج يكون فحالة ممتازة. صراحة أنا محبط بزاف وحاس براسي متجاهل.",
                offset: 44,
                duration: 10,
                sentiment: "negative",
                proposed_answer: "",
                tag: "استياء الزبون",
            },
            {
                speaker: "Agent",
                text: "واضح أن هادشي ماكانش الخدمة اللي كنتي كتسناها أو اللي كنطمحو نقدموها. سمح لي نتحقق من الطلبية ديالك باش نفهم شنو وقع. واش ممكن تعطيني رقم الطلبية ديالك، عفاك؟",
                offset: 54,
                duration: 12,
                sentiment: "neutral",
                proposed_answer: "",
                tag: "طلب معلومات ومحاولة حل",
            },
            {
                speaker: "Client",
                text: "رقم الطلبية ديالي هو 78 963 421.",
                offset: 67,
                duration: 4,
                sentiment: "neutral",
                proposed_answer: "",
                tag: "",
            },
            {
                speaker: "Agent",
                text: "شكرا. لحظة باش نتحقق منو. لقيت الطلبية ديالك، فعلا وصلات متأخرة 5 أيام، وكاين تسجيل بلي المنتج كان مخسر عند الاستلام.",
                offset: 72,
                duration: 13,
                sentiment: "neutral",
                proposed_answer: "",
                tag: "",
            },
            {
                speaker: "Client",
                text: "كنظن أنك فاهم بلي هادشي ماشي مقبول، خصوصا وأنا خلصت على التوصيل السريع. حتى زدت وتصلت بيكم باش نأكد كلشي بخير، وقيلوا لي كلشي غادي مزيان. ولكن دابا لقيت راسي بمنتوج مخسر وهادية العيد دازت بلا فايدة.",
                offset: 86,
                duration: 19,
                sentiment: "negative",
                proposed_answer: "",
                tag: "زبون غاضب ومحبط",
            },
            {
                speaker: "Agent",
                text: "كنعتذر بزاف على هاد الإزعاج، وغادي نخدم باش نلقى ليك حل فالحين. كنفهم الإحباط ديالك، وغادي نقترح عليك تبادل المنتج. نبعث ليك واحد جديد ونتكلفو بإرجاع المنتج المخسر. واش هاد الحل يعجبك؟",
                offset: 106,
                duration: 38,
                sentiment: "positif",
                proposed_answer: "نقترحو إرسال منتوج جديد وتكفل بإرجاع المنتج المخسر.",
                tag: "اقتراح حل وتبادل",
            },
            {
                speaker: "Client",
                text: "واخا، ولكن بغيت نتأكد أن هاد المرة كلشي غادي يكون مزبوط. حيت صراحة تعبني هادشي بعد ما خلصت على خدمة بريميوم.",
                offset: 125,
                duration: 7,
                sentiment: "negative",
                proposed_answer: "",
                tag: "",
            },
            {
                speaker: "Agent",
                text: "كنفهم، سيدي. غادي نتكلف شخصيا بالملف ديالك ونتصل بيك مباشرة منين يوصلك المنتج باش نتأكد كلشي مزيان. وفاش يكون أي مشكل، غادي نكون موجود باش نحلوا فالحين.",
                offset: 134,
                duration: 14,
                sentiment: "positif",
                proposed_answer: "",
                tag: "ضمان متابعة شخصية",
            },
        ],
    },
    {
        id: 8,
        resolved: 1,
        audio_path: "./audios/audio3.mp3",
        agent_id: 1,
        agent_name: "Mohamed Hanini",
        date: "02/04/2024",
        title: "Seeking Technical Support for a Malfunctioning Product",
        client_id: 96,
        client_name: "Ayoub Toudi",
        metadata: {
            demands:
                "- The client demanded accountability for the delayed and damaged product, citing their premium payment and expectations for high-quality service.<br>- They insisted on proper follow-up to ensure no recurrence of such issues in future orders.",
            actions:
                "- The agent apologized sincerely, acknowledged the client's frustration, and committed to resolving the problem.<br>- Proposed an exchange of the damaged product with expedited shipping and covered all return costs.<br>- Offered a 20% discount on a future purchase as a gesture of goodwill.<br>- Highlighted internal process improvements to avoid similar incidents in the future.",
            conclusion:
                "- The client accepted the proposed solutions, including the replacement and compensation, but emphasized their expectation for proper handling moving forward.  ",
            next_steps:
                "- The agent committed to following up personally after the client receives the replacement to ensure satisfaction.<br>- The company will implement process reviews to address logistic and quality issues raised in this case.<br>- The client awaits delivery of the replacement and will assess the company's actions before making decisions about future purchases.",
            sentiment_desc_client:
                "The client is initially frustrated and dissatisfied but becomes cautiously hopeful as solutions are proposed, though they remain skeptical about future service reliability.",
            sentiment_desc_agent:
                "The agent maintains a professional and empathetic tone throughout, focusing on resolving the issue, rebuilding trust, and ensuring the client feels valued.",
        },
        transcriptions: [
            {
                speaker: "Agent",
                text: "Bonjour, vous êtes bien au service Client 2. Je m'appelle Imane, comment puis-je vous aider aujourd'hui ?",
                offset: 0,
                duration: 5,
                sentiment: "neutral",
                tag: "",
            },
            {
                speaker: "Client",
                text: "Bonjour, je vous appelle parce que je suis vraiment mécontent de ma dernière commande. Je suis un client fidèle depuis plusieurs années, mais là, je trouve que le service est vraiment inacceptable.",
                offset: 5,
                duration: 10,
                sentiment: "negative",
                proposed_answer: "",
                tag: "insatisfaction du client",
            },
            {
                speaker: "Agent",
                text: "Je suis désolée d'apprendre que vous avez eu une mauvaise expérience, Monsieur. Je vous prie de bien vouloir m'expliquer ce qui s'est passé, je suis là pour vous aider à résoudre ce problème.",
                offset: 16,
                duration: 9,
                sentiment: "neutral",
                proposed_answer: "",
                tag: "",
            },
            {
                speaker: "Client",
                text: "Eh bien, j'ai passé commande d'un article important pour un cadeau d'anniversaire, et non seulement il est arrivé avec un retard de 5 jours, mais en plus, il était endommagé à l'intérieur de l'emballage. C'est vraiment frustrant.",
                offset: 26,
                duration: 9,
                sentiment: "negative",
                proposed_answer: "",
                tag: "client frustré",
            },
            {
                speaker: "Agent",
                text: "Je comprends totalement votre frustration, et je tiens à m'excuser sincèrement pour cette mauvaise expérience.",
                offset: 38,
                duration: 5,
                sentiment: "neutral",
                proposed_answer: "",
                tag: "rassurance du client",
            },
            {
                speaker: "Client",
                text: "Est payé pour une livraison express, et je m'attendais à ce que le produit soit en parfait état à la réception. Là, je suis très déçu, et je me sens un peu ignoré, pour être honnête.",
                offset: 44,
                duration: 10,
                sentiment: "negative",
                proposed_answer: "",
                tag: "insatisfaction du client",
            },
            {
                speaker: "Agent",
                text: "Il est évident que ce n'est pas le service que vous attendiez ni que nous souhaitons offrir à nos clients. Permettez-moi de vérifier votre commande pour comprendre ce qui a pu se passer. Pourriez-vous me communiquer votre numéro de commande, s'il vous plaît ?",
                offset: 54,
                duration: 12,
                sentiment: "neutral",
                proposed_answer: "",
                tag: "demande d'information et tentative de solution",
            },
            {
                speaker: "Client",
                text: "Le numéro de ma commande est le 78 963 421.",
                offset: 67,
                duration: 4,
                sentiment: "neutral",
                proposed_answer: "",
                tag: "",
            },
            {
                speaker: "Agent",
                text: "Merci. Un instant, je vais vérifier cela immédiatement. Alors, j'ai bien retrouvé votre commande. Je vois effectivement que le colis a pris plus de temps que prévu pour arriver, et je constate également qu'il a été signalé comme endommagé à la réception.",
                offset: 72,
                duration: 13,
                sentiment: "neutral",
                proposed_answer: "",
                tag: "",
            },
            {
                speaker: "Client",
                text: "Vous comprenez bien que ce genre de situation n'est pas acceptable, surtout quand on choisit une livraison express en payant plus cher. En plus, je vous avais même appelé avant la date prévue de livraison pour vérifier si tout était en ordre, et on m'avait assuré que tout irait bien. Là, je me retrouve avec un produit inutilisable, et l'anniversaire est déjà passé.",
                offset: 86,
                duration: 19,
                sentiment: "negative",
                proposed_answer: "",
                tag: "client en colère et déçu",
            },
            {
                speaker: "Agent",
                text: "Je suis sincèrement désolé pour ces désagréments, et je m'engage à trouver une solution rapidement. Je comprends pleinement votre frustration, et je vous assure que nous faisons de notre mieux pour éviter ce genre de situation. Il est clair que cette fois-ci, nous n'avons pas respecté nos engagements, et c'est tout à fait compréhensible que vous soyez déçus. J'aimerais vous proposer plusieurs solutions pour rectifier cette situation. Si vous le souhaitez, nous pouvons procéder à un échange du produit. Nous enverrons un nouvel article dans les plus brefs délais, et je vous garantis que cette fois-ci, tout sera vérifié avant expédition. Je peux également organiser un retour gratuit de l'article endommagé. Est-ce que cette solution vous conviendrait ?",
                offset: 106,
                duration: 38,
                sentiment: "positif",
                proposed_answer:
                    "Nous proposons d'envoyer un nouveau produit ainsi qu'un retour gratuit de l'article endommagé.",
                tag: "proposition de solution et échange",
            },
            {
                speaker: "Client",
                text: "Oui, mais je veux m'assurer que tout sera fait correctement cette fois. C'est vraiment pénible de devoir gérer tout ça après avoir déjà payé une somme importante pour un service premium.",
                offset: 125,
                duration: 7,
                sentiment: "negative",
                proposed_answer: "",
                tag: "",
            },
            {
                speaker: "Agent",
                text: "Je comprends parfaitement, monsieur. Vous avez raison, la situation n'aurait jamais dû en arriver là. Pour nous excuser de cet incident, nous allons nous occuper de l'échange du produit dans les 24 heures suivant l'autorisation de retour, et nous prendrons à notre charge tous les frais liés à ce retour. De plus, je vais m'assurer que le produit de remplacement soit expédié en priorité, pour que vous le receviez dans un délai de 48 heures maximum.",
                offset: 134,
                duration: 24,
                sentiment: "positif",
                proposed_answer: "",
                tag: "garantie de traitement rapide et sans frais",
            },
            {
                speaker: "Client",
                text: "D'accord, mais que puis-je faire pour m'assurer que ce genre de situation ne se reproduise pas à l'avenir ? Je veux bien accepter cette solution, mais je ne veux plus vivre ce genre de stress lors de mes prochaines commandes.",
                offset: 158,
                duration: 13,
                sentiment: "negative",
                proposed_answer: "",
                tag: "",
            },
            {
                speaker: "Agent",
                text: "Je vous remercie pour votre compréhension, et je tiens à vous rassurer, nous avons pris ce problème très au sérieux. Nous avons déjà lancé une révision de nos procédures logistiques afin d'éviter que ce genre de retard ne se produise. En outre, j'ai remonté votre dossier à notre équipe qualité pour qu'il renforce les contrôles avant l'expédition, surtout pour les produits fragiles.",
                offset: 171,
                duration: 20,
                sentiment: "positif",
                proposed_answer: "",
                tag: "amélioration des processus internes",
            },
            {
                speaker: "Agent",
                text: "Je vous propose également un geste commercial en guise de compensation pour cet incident. En plus de l'échange rapide du produit, nous vous offrons un bon de réduction de 20% valable sur votre prochaine commande. Vous recevrez un code promotionnel par e-mail dans les 24 heures. J'espère que ce geste vous apportera un peu plus de satisfaction.",
                offset: 191,
                duration: 18,
                sentiment: "positif",
                proposed_answer:
                    "On propose d'envoyer un nouveau produit et d'assurer un retour gratuit de l'article endommagé.",
                tag: "geste commercial de compensation",
            },
            {
                speaker: "Client",
                text: "C'est déjà un bon début, je vous remercie pour cela, mais j'aimerais aussi qu'il y ait un suivi plus rigoureux de votre part. Peut-être pourriez-vous me contacter directement pour vérifier que tout se passe bien après réception du nouvel article ?",
                offset: 209,
                duration: 11,
                sentiment: "positif",
                proposed_answer: "",
                tag: "Client satisifait",
            },
            {
                speaker: "Agent",
                text: "Absolument, monsieur. Je m'engage à suivre personnellement votre dossier, et dès que vous recevrez votre nouvel article, je vous contacterai pour m'assurer que tout est en ordre. Si jamais il y a le moindre problème, je serai là pour le résoudre immédiatement.",
                offset: 220,
                duration: 14,
                sentiment: "positif",
                proposed_answer: "",
                tag: "assurance de suivi personnalisé",
            },
            {
                speaker: "Client",
                text: "Bon, je suis plutôt rassuré par vos efforts, mais je vous assure que la prochaine fois, je n'hésiterai pas à chercher ailleurs si je fais encore face à ce genre de problème. J'attends que vous soyez à la hauteur de vos promesses.",
                offset: 234,
                duration: 11,
                sentiment: "neutral",
                proposed_answer: "",
                tag: "client encore méfiant",
            },
            {
                speaker: "Agent",
                text: "Je comprends tout à fait vos inquiétudes, et je vous promets que nous ferons tout pour regagner votre confiance. Nous apprécions énormément nos clients fidèles comme vous, et nous ne voulons pas que cette situation affecte notre relation à long terme. Votre satisfaction est notre priorité, et je serai là pour vous accompagner tout au long de ce processus.",
                offset: 245,
                duration: 21,
                sentiment: "positif",
                proposed_answer: "",
                tag: "rassurance du client et engagement",
            },
            {
                speaker: "Client",
                text: "Très bien, j'attends de voir comme tout cela va se dérouler.",
                offset: 266,
                duration: 5,
                sentiment: "neutral",
                proposed_answer: "",
                tag: "attente du client",
            },
            {
                speaker: "Agent",
                text: "Merci pour votre réactivité et pour avoir pris le temps de m'écouter.",
                offset: 271,
                duration: 4,
                sentiment: "positif",
                proposed_answer: "",
                tag: "remerciement et clôture",
            },
        ],
    },
    // {
    // resolved: 1,
    // audio_path: "./audios/audio1.mp3",
    //     agent_id: 1,
    //     agent_name: "agent name",
    //     date: "12/04/2024",
    //     title: "this is the title",
    //     client_id: 2,
    //     client_name: "client name",
    // },
    // {
    // resolved: 1,
    // audio_path: "./audios/audio1.mp3",
    //     agent_id: 12,
    //     agent_name: "agent name",
    //     date: "12/04/2024",
    //     title: "this is the title",
    //     client_id: 3,
    //     client_name: "client name",
    // },
    // {
    // resolved: 1,
    // audio_path: "./audios/audio1.mp3",
    //     agent_id: 1,
    //     agent_name: "agent name",
    //     date: "12/04/2024",
    //     title: "this is the title",
    //     client_id: 3,
    //     client_name: "client name",
    // },
    // {
    // resolved: 1,
    // audio_path: "./audios/audio1.mp3",
    //     agent_id: 1,
    //     agent_name: "agent name",
    //     date: "12/04/2024",
    //     title: "this is the title",
    //     client_id: 3,
    //     client_name: "client name",
    // },
    // {
    // resolved: 1,
    // audio_path: "./audios/audio1.mp3",
    //     agent_id: 1,
    //     agent_name: "agent name",
    //     date: "12/04/2024",
    //     title: "this is the title",
    //     client_id: 1,
    //     client_name: "client name 1112",
    // },
];
